// Code generated by optionsgen. DO NOT EDIT.

package runtime

import (
	"os"
	"time"

	runtime "github.com/compozy/compozy/engine/runtime"
)

type Option func(*runtime.Config)

// WithBackoffInitialInterval sets the BackoffInitialInterval field
func WithBackoffInitialInterval(backoffInitialInterval time.Duration) Option {
	return func(cfg *runtime.Config) {
		cfg.BackoffInitialInterval = backoffInitialInterval
	}
}

// WithBackoffMaxInterval sets the BackoffMaxInterval field
func WithBackoffMaxInterval(backoffMaxInterval time.Duration) Option {
	return func(cfg *runtime.Config) {
		cfg.BackoffMaxInterval = backoffMaxInterval
	}
}

// WithBackoffMaxElapsedTime sets the BackoffMaxElapsedTime field
func WithBackoffMaxElapsedTime(backoffMaxElapsedTime time.Duration) Option {
	return func(cfg *runtime.Config) {
		cfg.BackoffMaxElapsedTime = backoffMaxElapsedTime
	}
}

// WithWorkerFilePerm sets the WorkerFilePerm field
func WithWorkerFilePerm(workerFilePerm os.FileMode) Option {
	return func(cfg *runtime.Config) {
		cfg.WorkerFilePerm = workerFilePerm
	}
}

// WithToolExecutionTimeout sets the ToolExecutionTimeout field
func WithToolExecutionTimeout(toolExecutionTimeout time.Duration) Option {
	return func(cfg *runtime.Config) {
		cfg.ToolExecutionTimeout = toolExecutionTimeout
	}
}

// WithRuntimeType sets the RuntimeType field
//
// Runtime selection fields
func WithRuntimeType(runtimeType string) Option {
	return func(cfg *runtime.Config) {
		cfg.RuntimeType = runtimeType
	}
}

// WithEntrypointPath sets the EntrypointPath field
func WithEntrypointPath(entrypointPath string) Option {
	return func(cfg *runtime.Config) {
		cfg.EntrypointPath = entrypointPath
	}
}

// WithBunPermissions sets the BunPermissions field
func WithBunPermissions(bunPermissions []string) Option {
	return func(cfg *runtime.Config) {
		cfg.BunPermissions = bunPermissions
	}
}

// WithNodeOptions sets the NodeOptions field
func WithNodeOptions(nodeOptions []string) Option {
	return func(cfg *runtime.Config) {
		cfg.NodeOptions = nodeOptions
	}
}

// WithNativeTools sets the NativeTools field
func WithNativeTools(nativeTools *runtime.NativeToolsConfig) Option {
	return func(cfg *runtime.Config) {
		cfg.NativeTools = nativeTools
	}
}

// WithEnvironment sets the Environment field
//
// Application config integration fields
func WithEnvironment(environment string) Option {
	return func(cfg *runtime.Config) {
		cfg.Environment = environment
	}
}

// WithMaxMemoryMB sets the MaxMemoryMB field
//
// Memory management
func WithMaxMemoryMB(maxMemoryMB int) Option {
	return func(cfg *runtime.Config) {
		cfg.MaxMemoryMB = maxMemoryMB
	}
}

// WithMaxStderrCaptureSize sets the MaxStderrCaptureSize field
func WithMaxStderrCaptureSize(maxStderrCaptureSize int) Option {
	return func(cfg *runtime.Config) {
		cfg.MaxStderrCaptureSize = maxStderrCaptureSize
	}
}
